<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            margin: 0;
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            background: #f5e6e8;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }

        .scrapbook {
            background: #fff;
            width: 90%;
            max-width: 800px;
            min-height: 600px;
            margin: 20px;
            padding: 40px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.1);
            border-radius: 10px;
            position: relative;
        }

        .page {
            display: none;
            animation: fadeIn 1s;
        }

        .page.active {
            display: block;
        }

        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }

        .polaroid {
            background: white;
            padding: 15px 15px 40px 15px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
            transform: rotate(-2deg);
            width: fit-content;
            margin: 20px auto;
            transition: transform 0.3s;
        }

        .polaroid:hover {
            transform: rotate(0deg) scale(1.02);
        }

        .photo {
            width: 300px;
            height: 300px;
            object-fit: cover;
            border: 1px solid #eee;
        }

        .caption {
            font-family: 'Courier New', Courier, monospace;
            margin-top: 10px;
            font-size: 16px;
            color: #333;
            text-align: center;
        }

        .message {
            font-family: 'Brush Script MT', cursive;
            font-size: 28px;
            color: #ff4b6e;
            text-align: center;
            margin: 30px 0;
            line-height: 1.4;
        }

        .sticker {
            position: absolute;
            font-size: 40px;
            transform: rotate(15deg);
            cursor: pointer;
            transition: transform 0.3s;
        }

        .sticker:hover {
            transform: rotate(0deg) scale(1.2);
        }

        .navigation {
            display: flex;
            justify-content: center;
            gap: 20px;
            margin-top: 30px;
        }

        .nav-button {
            background: #ff4b6e;
            color: white;
            border: none;
            padding: 15px 30px;
            font-size: 18px;
            border-radius: 25px;
            cursor: pointer;
            transition: transform 0.2s;
        }

        .nav-button:hover {
            transform: scale(1.05);
        }

        .tape {
            position: absolute;
            background: rgba(255,255,255,0.6);
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            width: 100px;
            height: 30px;
            transform: rotate(-45deg);
        }

        .final-page {
            text-align: center;
        }

        .choice-buttons {
            display: flex;
            justify-content: center;
            gap: 20px;
            margin-top: 30px;
        }

        #noBtn {
            background: #666;
        }

        .hearts-container {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            pointer-events: none;
            z-index: 1000;
        }
    </style>
</head>
<body>
    <div class="scrapbook">
        <!-- Page 1 -->
        <div class="page active" id="page1">
            <div class="message">Our Story...</div>
            <div class="polaroid">
                <div class="tape"></div>
                <img class="photo" src="/api/placeholder/300/300" alt="First memory">
                <div class="caption">Remember when we first met? 💕</div>
            </div>
            <div class="sticker" style="right: 50px; top: 50px">💝</div>
            <div class="navigation">
                <button class="nav-button" onclick="nextPage(2)">Turn Page ➡️</button>
            </div>
        </div>

        <!-- Page 2 -->
        <div class="page" id="page2">
            <div class="polaroid">
                <div class="tape"></div>
                <img class="photo" src="/api/placeholder/300/300" alt="Second memory">
                <div class="caption">Every moment with you is magical ✨</div>
            </div>
            <div class="sticker" style="left: 60px; bottom: 100px">🌟</div>
            <div class="navigation">
                <button class="nav-button" onclick="nextPage(3)">Next Page ➡️</button>
            </div>
        </div>

        <!-- Page 3 -->
        <div class="page" id="page3">
            <div class="polaroid">
                <div class="tape"></div>
                <img class="photo" src="/api/placeholder/300/300" alt="Third memory">
                <div class="caption">You make me smile in ways I never knew possible 😊</div>
            </div>
            <div class="sticker" style="right: 80px; bottom: 120px">🌸</div>
            <div class="navigation">
                <button class="nav-button" onclick="nextPage(4)">Keep Going ➡️</button>
            </div>
        </div>

        <!-- Page 4 -->
        <div class="page" id="page4">
            <div class="polaroid">
                <div class="tape"></div>
                <img class="photo" src="/api/placeholder/300/300" alt="Fourth memory">
                <div class="caption">And now I want to ask you something special...</div>
            </div>
            <div class="sticker" style="left: 70px; top: 80px">💫</div>
            <div class="navigation">
                <button class="nav-button" onclick="nextPage(5)">Almost There ➡️</button>
            </div>
        </div>

        <!-- Final Page -->
        <div class="page" id="page5">
            <div class="message">Will you be my girlfriend? 💝</div>
            <div class="polaroid">
                <div class="tape"></div>
                <img class="photo" src="/api/placeholder/300/300" alt="Our favorite moment">
                <div class="caption">Us, forever? 💕</div>
            </div>
            <div class="choice-buttons">
                <button class="nav-button" onclick="handleYes()">Yes! 💗</button>
                <button class="nav-button" id="noBtn" onmouseover="moveButton()">No</button>
            </div>
        </div>

        <!-- Success Page -->
        <div class="page" id="success">
            <div class="message">You've made me the happiest person! 💖</div>
            <div class="polaroid">
                <div class="tape"></div>
                <img class="photo" src="/api/placeholder/300/300" alt="Celebration photo">
                <div class="caption">Here's to our beginning! 🎉</div>
            </div>
        </div>
    </div>

    <script>
        function nextPage(pageNumber) {
            document.querySelector('.page.active').classList.remove('active');
            document.getElementById('page' + pageNumber).classList.add('active');
        }

        function moveButton() {
            const btn = document.getElementById('noBtn');
            const scrapbook = document.querySelector('.scrapbook');
            const maxX = scrapbook.clientWidth - btn.clientWidth - 50;
            const maxY = scrapbook.clientHeight - btn.clientHeight - 50;
            
            btn.style.position = 'absolute';
            btn.style.left = Math.random() * maxX + 'px';
            btn.style.top = Math.random() * maxY + 'px';
        }

        function handleYes() {
            document.querySelector('.page.active').classList.remove('active');
            document.getElementById('success').classList.add('active');
            createHearts();
        }

        function createHearts() {
            setInterval(() => {
                const heart = document.createElement('div');
                heart.innerHTML = '❤️';
                heart.style.position = 'fixed';
                heart.style.fontSize = Math.random() * 30 + 20 + 'px';
                heart.style.left = Math.random() * 100 + 'vw';
                heart.style.top = '100vh';
                heart.style.opacity = '0.8';
                heart.style.transition = 'all 3s ease-out';
                document.body.appendChild(heart);

                setTimeout(() => {
                    heart.style.top = '0vh';
                    heart.style.opacity = '0';
                }, 100);

                setTimeout(() => {
                    document.body.removeChild(heart);
                }, 3000);
            }, 300);
        }
    </script>
</body>
</html>
